### ISSUE TITLE
Define variable Delta t

### ISSUE THREAD

**Issue by dominikstaltner** [sebastianpech/TexVar#1]
Hello Mr. Pech,

firstly I want to thank you for your nice TexVar-Package. Since a few days I'm trying it and I like it a lot.

Now to my question:

Is there a way to define a variable in the tvar-environment with the name \\Delta t? It possible to define \\Delta\\tau or t\\Delta, but I haven't found a way to define \\Delta t.

Please could you help me?

Regards,
Dominik

**Comment by sebastianpech** [comment]
Thanks for your kind words. So this is actually a flaw in the simplified input system. What you can do is define the variable directly with `tVar:New`.
```
\begin{tVar}
   d_t = tVar:New(10.1,"\\Delta t"):outRES()
   A := d_t^2
\end{tVar}
```
`"\\Delta t"` is the LaTeX representation and `10.1` the value.

**Comment by dominikstaltner** [comment]
Hello Mr. Pech,

thanks a lot for your helpful answer. I've tried it and it worked perfectly.

But for the future, it would be very nice to define a variable like "Delta t" in the same way as "Delta tau" (double\Deltadouble\tau:=...).

Regards,
Dominik

**Comment by sebastianpech** [comment]
The thing is that `\Delta\tau` can be parsed because `\Delta` and `\tau` are recognized as different control sequences in LaTeX. `\Deltat` however, doesn't mean anything because there is no command `Deltat`.

So I would need a syntax for separating the t from the `\Delta`. In LaTeX you can just add a space because it's removed (or do `\Delta{}t`). However, the choosen name also needs to be a valid variable name, so spaces and braces are not suitable and underscores are already taken by sub- and superscript. 

An alternative to the approach above would be to actually define a new command `\Deltat` in your LaTeX preamble:
```tex
\newcommand{\Deltat}{\Delta{}t}
```
In the TexVar-env you can now do smth like this:
```tex
\begin{tVar}
   \\Deltat := 10.1
   A := Deltat^2
\end{tVar}
```
I haven't tested it but it should work.

**Comment by dominikstaltner** [comment]
Thank you very much again for your help. That's what I was looking for.
